image: linuxkit-bitnami-openldap
config:
  binds:
    - /etc/resolv.conf:/etc/resolv.conf:ro
  capabilities:
    - CAP_NET_BIND_SERVICE
    - CAP_SYS_CHROOT
    - CAP_SETGID
    - CAP_SETUID
    - CAP_CHOWN
    - CAP_KILL
    - CAP_MKNOD
    - CAP_SETPCAP
    - CAP_SETFCAP
    - CAP_FSETID
    - CAP_FOWNER
    - CAP_DAC_OVERRIDE
    - CAP_AUDIT_WRITE
  net: host
  ipc: new
  uid: 1001

